class Error(Exception):
    pass


class UnrecoverableError(Error):
    pass
